name: Check RetroAchievements

on:
  schedule:
    - cron: "*/10 * * * *"  # Every 10 minutes
  workflow_dispatch:

jobs:
  check_achievements:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install requests

      - name: Run checker
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: python check_achievements.py

      - name: Commit updated users.json
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add users.json
          git commit -m "Update last_check timestamps" || echo "No changes"
          git push
