name: Test Discord Embed

on:
  workflow_dispatch:

jobs:
  test-discord:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install requests
        working-directory: ./Retro-Achievements-Discord-Tracker

      - name: Run test embed post
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: python post_to_discord_embed.py
        working-directory: ./Retro-Achievements-Discord-Tracker
